title: simondotsh's infosec stuff
baseurl: "/"
url: "https://simondotsh.com"
twitter_username: simondotsh
github_username:  simondotsh
mastodon:
- username: simondotsh
  instance: infosec.exchange

# Build settings
theme: minima
plugins:
  - jekyll-feed
