title: simondotsh's infosec stuff
baseurl: "/"
url: "https://simondotsh.com"
twitter_username: simondotsh
github_username:  simondotsh

# Build settings
theme: minima
plugins:
  - jekyll-feed
